server.port: ${PORT:8080}
logging.level.org.atmosphere: warn
spring.mustache.check-template-location: false




spring:
  jpa:
    database: POSTGRESQL
    how-sql: false
    hibernate.ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/project_manager
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  database.driverClassName: org.postgresql.Driver


jwt.secret: ${JWT_TOKEN}


